server:
  # 端口
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eladmin?serverTimezone=Asia/Shanghai
    username: eladmin
    password: eladmin
    main:
        allow-bean-definition-overriding: true
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

aes:
  secret:
    key: evan123456789012

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒），设置为 10 分钟（600 秒）
  timeout: 600
  # 是否从 cookie 中读取 token
  is-read-cookie: true
  # token 最低活跃频率（单位：秒），设置为 5 分钟（300 秒）
  active-timeout: 300
  check-permission: true
  check-login: true
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  # 是否输出操作日志
  is-log: true
  # 打开 RPC 调用鉴权
  check-same-token: true

logging:
  level:
    com:
      baomidou:
        mybatisplus: OFF
    org:
      mybatis:
        spring: OFF


mybatis:
  configuration:
    map-underscore-to-camel-case: true

